### ISSUE TITLE
Import snapshot data locally (non-RDS)

### ISSUE THREAD

**Issue by timkelty** [binbashar/terraform-aws-rds-export-to-s3#1]
I wanted to use this module to export backups to S3, for devs to download and use for local development.
If I'm reading correctly, this is exporting the snapshot, so it would be in Parquet SerDe.

Do you have any tips for extracting a mysql/postgres dump from this?

**Comment by vmalinics0** [comment]
Hope that helps:

`When you export a DB snapshot, Amazon RDS extracts data from the snapshot and stores it in an Amazon S3 bucket in your account. The data is stored in an Apache Parquet format that is compressed and consistent. `

`After the data is exported, you can analyze the exported data directly through tools like Amazon Athena or Amazon Redshift Spectrum. For more information on using Athena to read Parquet data, see Parquet SerDe in the Amazon Athena User Guide. For more information on using Redshift Spectrum to read Parquet data, see COPY from columnar data formats in the Amazon Redshift Database Developer Guide. `

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ExportSnapshot.html
https://docs.aws.amazon.com/athena/latest/ug/parquet-serde.html

**Comment by exequielrafaela** [comment]
@timkelty thanks for your contact, I think @vmalinics0 comment answers your query. Hope that helps.

CC: @binbashar/leverage-ref-architecture-aws-dev @binbashar/leverage-ref-architecture-aws-admin
