### ISSUE TITLE
Can't trigger from manual snapshots

### ISSUE THREAD

**Issue by ejskipper** [binbashar/terraform-aws-rds-export-to-s3#12]
I've just set up this module and wanted to allow triggering from manual snapshots for testing. I passed `rds_event_ids = "RDS-EVENT-0075, RDS-EVENT-0169"` to the module. However it seems that it's not possible to name the snapshot in such a way that it will match the regex given on line 37 of `functions/export-to-s3/index.py`
`"^rds:" + db + "-\d{4}-\d{2}-\d{2}-\d{2}-\d{2}$"` => AWS does not allow colons in the name of manual snapshots so this can't be matched.

Also worth noting, I had an error where I didn't include   `snapshots_bucket_prefix`  in the inputs and Python crashed. Not sure if it's supposed to be required but this doesn't seem to be stated in the docs.

Happy to open a PR for this if helpful. Thanks for the work on the module!

**Comment by exequielrafaela** [comment]
@ejskipper Thanks for reporting this issue, we'll review it and try to prioritize it with the team as soon as we can. If you would like to open a PR with the suggested fix that would really helpful and welcome.

CC: @binbashar/leverage-project-terraform-admin @binbashar/leverage-project-terraform-dev

**Comment by ejskipper** [comment]
Thanks! I've opened a PR now

**Comment by exequielrafaela** [comment]
@ejskipper that's great @eze-godoy we'll be working on its review and we'll let you know. Thanks!

**Comment by exequielrafaela** [comment]
Thanks to both @ejskipper and @eze-godoy
Closing Issue with associated PR https://github.com/binbashar/terraform-aws-rds-export-to-s3/pull/13

**Comment by ejskipper** [comment]
Hi @exequielrafaela - thanks for the review and merge! Just wanted to check when I can expect this to be released please?

Also, I noticed I had a typo in the markdown for README, so opened another PR if you want to correct it.
#14 

Edit: thanks for the release!

**Comment by exequielrafaela** [comment]
@ejskipper Ellen, we released version [v0.4.2](https://github.com/binbashar/terraform-aws-rds-export-to-s3/releases/tag/v0.4.2) last week. Please let us know how the implementation goes 🚀.

We truly appreciate your outstanding contribution to this project. We'd be thrilled if you'd consider joining our binbash Leverage community on [Slack (click to join ❤️ )](https://join.slack.com/t/binbashar/shared_invite/zt-fw1692b6-9k4ADsWJ47lKacszphXM1w). It would serve as a direct communication channel for any future development and support requests you might have. :) Hope to see you there!!!
