### ISSUE TITLE
Update aws lambda module version

### ISSUE THREAD

**Issue by southeo** [binbashar/terraform-aws-rds-export-to-s3#15]
Hello, 

I noticed the terraform lambda module version used here is several major versions behind most [up to-date deployment](https://github.com/terraform-aws-modules/terraform-aws-lambda). v2.23.0 relies on depreciated resources (namely the `aws_s3_bucket_object` instead of the `aws_s3_object`). Would be great to see this module brought more up to-date.

**Comment by eze-godoy** [comment]
Hello @southeo! We just merged the update you suggested to the module, and we hope you find it usefull. Thanks!
